const e=require('express'),c=require('cors'),b=require('bcryptjs'),j=require('jsonwebtoken'),p=require('path'),f=require('fs');
const P=p.join(__dirname,'data.json');
function L(){try{if(f.existsSync(P))return JSON.parse(f.readFileSync(P,'utf8'))}catch(e){}return U()}
function S(){f.writeFileSync(P,JSON.stringify(d,null,2),'utf8')}
function U(){return{users:[{id:'super-1',username:'admin',password:b.hashSync('admin',10),display_name:'超级管理员',role:'super_admin',created_at:N()}],user_data:{},settings:{low_threshold:10,critical_threshold:3,shop_name:'我的便利店',categories:['饮料','零食','方便食品','日用品','烟酒','冷藏食品','调味品']}}}
let d=L();
// 重置 admin 密码为 admin
const adminUser = d.users.find(u => u.username === 'admin' && u.role === 'super_admin');
if (adminUser) { adminUser.password = b.hashSync('admin', 10); }
function E(u){if(!d.user_data[u])d.user_data[u]={products:[],stock_log:[],sales:[]};return d.user_data[u]}
function N(){const e=new Date();return new Date(e.getTime()+28800000).toISOString().replace('T',' ').slice(0,19)}
function D(){return N().slice(0,10)}
function R(s,e){return{start:s?s+' 00:00:00':'2000-01-01 00:00:00',end:e?e+' 23:59:59':'2099-12-31 23:59:59'}}
const a=e();const O=process.env.PORT||3000,K=process.env.JWT_SECRET||'cvs-secret';
a.use(c());a.use(e.json());a.use(e.static(p.join(__dirname,'public')));
function A(r,_,n){const h=r.headers.authorization;if(!h||!h.startsWith('Bearer '))return _.status(401).json({error:'未登录'});try{r.user=j.verify(h.slice(7),K);n()}catch(e){return _.status(401).json({error:'已过期'})}}
function SA(r,_,n){if(r.user.role!=='super_admin')return _.status(403).json({error:'仅超级管理员'});n()}
function AO(r,_,n){if(r.user.role==='cashier')return _.status(403).json({error:'收银员无权限'});n()}
function I(){return Date.now().toString(36)+Math.random().toString(36).slice(2,6)}
setInterval(()=>{const t=new Date(Date.now()-7776000000+28800000).toISOString().replace('T',' ').slice(0,19);for(const u in d.user_data)d.user_data[u].stock_log=d.user_data[u].stock_log.filter(l=>l.time>=t);S()},86400000);
a.post('/api/login',(r,_)=>{const{username,password}=r.body;if(!username||!password)return _.status(400).json({error:'请输入账号和密码'});const u=d.users.find(x=>x.username===username);if(!u)return _.status(400).json({error:'该账号不存在'});if(!b.compareSync(password,u.password))return _.status(400).json({error:'密码错误'});const t=j.sign({id:u.id,username:u.username,display_name:u.display_name,role:u.role},K,{expiresIn:'30d'});E(u.id);S();_.json({token:t,user:{id:u.id,username:u.username,display_name:u.display_name,role:u.role}})});
a.get('/api/me',A,(r,_)=>_.json({user:r.user}));
a.get('/api/users',A,SA,(r,_)=>_.json(d.users.map(u=>({id:u.id,username:u.username,display_name:u.display_name,role:u.role,created_at:u.created_at}))));
a.post('/api/users',A,SA,(r,_)=>{const{username,password,display_name,role}=r.body;if(!username||!password||!display_name)return _.status(400).json({error:'请填写完整'});if(d.users.find(u=>u.username===username))return _.status(400).json({error:'账号已存在'});const i=I();d.users.push({id:i,username,password:b.hashSync(password,10),display_name,role:role||'admin',created_at:N()});E(i);S();_.json({success:true,id:i})});
a.put('/api/users/:id',A,SA,(r,_)=>{const u=d.users.find(x=>x.id===r.params.id);if(!u)return _.status(404).json({error:'不存在'});if(u.role==='super_admin')return _.status(400).json({error:'不可修改超级管理员'});if(r.body.display_name)u.display_name=r.body.display_name;if(r.body.role)u.role=r.body.role;if(r.body.password)u.password=b.hashSync(r.body.password,10);S();_.json({success:true})});
a.delete('/api/users/:id',A,SA,(r,_)=>{const i=d.users.findIndex(x=>x.id===r.params.id);if(i===-1)return _.status(404).json({error:'不存在'});if(d.users[i].role==='super_admin')return _.status(400).json({error:'不可删除超级管理员'});d.users.splice(i,1);delete d.user_data[r.params.id];S();_.json({success:true})});
a.get('/api/products',A,(r,_)=>{const u=r.user.id;const dt=E(u);let l=[...dt.products];const{s,c,ss}=r.query,{low_threshold:lo,critical_threshold:cr}=d.settings;if(s){const q=s.toLowerCase();l=l.filter(p=>p.name.toLowerCase().includes(q)||(p.barcode&&p.barcode.includes(q))||(p.supplier&&p.supplier.toLowerCase().includes(q)))}if(c)l=l.filter(p=>p.category===c);if(ss==='normal')l=l.filter(p=>p.qty>lo);else if(ss==='low')l=l.filter(p=>p.qty<=lo&&p.qty>cr);else if(ss==='critical')l=l.filter(p=>p.qty<=cr);_.json(l)});
a.post('/api/products',A,AO,(r,_)=>{const u=r.user.id;const dt=E(u);const{name,barcode,category,supplier,qty,min_stock,cost,price,shelf}=r.body;if(!name||!category)return _.status(400).json({error:'请填写名称和分类'});const i=I();dt.products.push({id:i,name,barcode:barcode||'',category,supplier:supplier||'',qty:qty||0,min_stock:min_stock||5,cost:cost||0,price:price||0,shelf:shelf||'',created_at:N(),updated_at:N()});S();_.json({success:true,id:i})});
a.put('/api/products/:id',A,AO,(r,_)=>{const u=r.user.id;const dt=E(u);const p=dt.products.find(x=>x.id===r.params.id);if(!p)return _.status(404).json({error:'不存在'});Object.assign(p,r.body);p.updated_at=N();S();_.json({success:true})});
a.delete('/api/products/:id',A,AO,(r,_)=>{const u=r.user.id;E(u).products=E(u).products.filter(x=>x.id!==r.params.id);S();_.json({success:true})});
function Lg(uid,pid,pn,ty,q,n,op){const dt=E(uid);const t=new Date(Date.now()-7776000000+28800000).toISOString().replace('T',' ').slice(0,19);dt.stock_log=dt.stock_log.filter(l=>l.time>=t);dt.stock_log.push({time:N(),product_id:pid,product_name:pn,type:ty,qty:q,note:n||'',operator:op||''})}
a.post('/api/stock/in',A,AO,(r,_)=>{const u=r.user.id;const dt=E(u);const{product_id,qty,cost,note,manual_product}=r.body;if(!qty||qty<1)return _.status(400).json({error:'数量无效'});let p;if(manual_product){if(!manual_product.name||!manual_product.category)return _.status(400).json({error:'请填写名称和分类'});const i=I();p={id:i,name:manual_product.name,barcode:manual_product.barcode||'',category:manual_product.category,supplier:manual_product.supplier||'',qty:0,min_stock:manual_product.min_stock||5,cost:0,price:manual_product.price||0,shelf:manual_product.shelf||'',created_at:N(),updated_at:N()};dt.products.push(p)}else{if(!product_id)return _.status(400).json({error:'请选择商品'});p=dt.products.find(x=>x.id===product_id);if(!p)return _.status(404).json({error:'不存在'})}p.qty+=qty;if(cost!==undefined&&cost>0)p.cost=cost;p.updated_at=N();Lg(u,p.id,p.name,'in',qty,note||'入库',r.user.display_name);S();_.json({success:true,product:p})});
a.post('/api/stock/out',A,AO,(r,_)=>{const u=r.user.id;const dt=E(u);const{product_id,qty,price,note}=r.body;if(!qty||qty<1)return _.status(400).json({error:'数量无效'});if(!product_id)return _.status(400).json({error:'请选择商品'});const p=dt.products.find(x=>x.id===product_id);if(!p)return _.status(404).json({error:'不存在'});if(qty>p.qty)return _.status(400).json({error:'库存不足！当前: '+p.qty});p.qty-=qty;if(price!==undefined&&price>0)p.price=price;p.updated_at=N();Lg(u,p.id,p.name,'out',qty,note||'出库',r.user.display_name);S();_.json({success:true,product:p})});
a.post('/api/sell',A,(r,_)=>{const u=r.user.id;const dt=E(u);const{items}=r.body;if(!items||!Array.isArray(items)||!items.length)return _.status(400).json({error:'请添加商品'});const sl=[];for(const x of items){const p=dt.products.find(p=>p.id===x.product_id);if(!p)return _.status(404).json({error:'商品不存在'});if(x.qty>p.qty)return _.status(400).json({error:'「'+p.name+'」库存不足'});sl.push({product_id:p.id,product_name:p.name,qty:x.qty,price:x.price||p.price,subtotal:(x.price||p.price)*x.qty})}const t=sl.reduce((s,i)=>s+i.subtotal,0),sI=I();for(const s of sl){const p=dt.products.find(x=>x.id===s.product_id);p.qty-=s.qty;Lg(u,p.id,p.name,'sell',s.qty,'销售',r.user.display_name)}dt.sales.push({id:sI,total:t,items:JSON.stringify(sl),operator:r.user.display_name,status:'completed',created_at:N()});S();_.json({success:true,sale_id:sI,total:t,items:sl})});
a.get('/api/logs',A,(r,_)=>{const u=r.user.id;const dt=E(u);const{type,start_date,end_date,page=1,page_size=50}=r.query;let l=dt.stock_log.map((x,i)=>({...x,_idx:i}));if(type)l=l.filter(x=>x.type===type);const{start,end}=R(start_date,end_date);l=l.filter(x=>x.time>=start&&x.time<=end).sort((a,b)=>b.time.localeCompare(a.time));const tl=l.length,ps=parseInt(page_size),p=parseInt(page);_.json({logs:l.slice((p-1)*ps,p*ps),total:tl,page:p,page_size:ps,total_pages:Math.ceil(tl/ps)})});
a.get('/api/sell-logs',A,(r,_)=>{const u=r.user.id;const dt=E(u);const{search,start_date,end_date,page=1,page_size=50}=r.query;let l=dt.stock_log.map((x,i)=>({...x,_idx:i}));l=l.filter(x=>x.type==='sell');const{start,end}=R(start_date,end_date);l=l.filter(x=>x.time>=start&&x.time<=end);if(search){const s=search.toLowerCase();l=l.filter(x=>x.product_name.toLowerCase().includes(s))}l.sort((a,b)=>b.time.localeCompare(a.time));const tl=l.length,ps=parseInt(page_size),p=parseInt(page);_.json({logs:l.slice((p-1)*ps,p*ps),total:tl,page:p,page_size:ps,total_pages:Math.ceil(tl/ps)})});
a.post('/api/sell-logs/:idx/revert',A,(r,_)=>{const u=r.user.id;const dt=E(u);const idx=parseInt(r.params.idx);if(isNaN(idx)||idx<0||idx>=dt.stock_log.length)return _.status(404).json({error:'记录不存在'});const log=dt.stock_log[idx];if(log.type!=='sell')return _.status(400).json({error:'只能撤回售出'});const p=dt.products.find(x=>x.id===log.product_id);if(p){p.qty+=log.qty;p.updated_at=N()}dt.stock_log.splice(idx,1);S();_.json({success:true,message:'已撤回，库存已恢复'})});
a.get('/api/dashboard',A,(r,_)=>{const u=r.user.id;const dt=E(u);const{low_threshold:lo,critical_threshold:cr}=d.settings;const tS=D()+' 00:00:00',tE=D()+' 23:59:59';const tSls=dt.sales.filter(s=>s.created_at>=tS&&s.created_at<=tE),tSll=dt.stock_log.filter(l=>l.time>=tS&&l.time<=tE&&l.type==='sell'),tIn=dt.stock_log.filter(l=>l.time>=tS&&l.time<=tE&&l.type==='in');_.json({totalProducts:dt.products.length,totalValue:dt.products.reduce((s,p)=>s+(p.qty||0)*(p.cost||0),0),lowStock:dt.products.filter(p=>p.qty<=lo&&p.qty>cr).length,criticalStock:dt.products.filter(p=>p.qty<=cr).length,lowItems:dt.products.filter(p=>p.qty<=lo).sort((a,b)=>a.qty-b.qty),todaySales:{count:tSls.length,total:tSls.reduce((s,x)=>s+x.total,0),sellQty:tSll.reduce((s,l)=>s+l.qty,0),inQty:tIn.reduce((s,l)=>s+l.qty,0)},recentLogs:dt.stock_log.slice(-10).reverse()})});
a.get('/api/reports',A,(r,_)=>{const u=r.user.id;const dt=E(u);const{start_date,end_date}=r.query;const{start,end}=R(start_date,end_date);const l=dt.stock_log.filter(l=>l.time>=start&&l.time<=end),sl=dt.sales.filter(s=>s.created_at>=start&&s.created_at<=end);const cm={};dt.products.forEach(p=>{const c=p.category||'未分类';if(!cm[c])cm[c]={count:0,qty:0,value:0};cm[c].count++;cm[c].qty+=p.qty||0;cm[c].value+=(p.qty||0)*(p.cost||0)});const sL=l.filter(x=>x.type==='sell'),iL=l.filter(x=>x.type==='in'),oL=l.filter(x=>x.type==='out');const sM={};sL.forEach(l=>{if(!sM[l.product_name])sM[l.product_name]={name:l.product_name,qty:0,count:0};sM[l.product_name].qty+=l.qty;sM[l.product_name].count++});_.json({summary:{totalSales:sl.reduce((s,x)=>s+x.total,0),totalSellQty:sL.reduce((s,l)=>s+l.qty,0),totalSellItems:sL.length,totalInQty:iL.reduce((s,l)=>s+l.qty,0),totalInCount:iL.length,totalOutQty:oL.reduce((s,l)=>s+l.qty,0)},categoryReport:cm,topSell:Object.values(sM).sort((a,b)=>b.qty-a.qty).slice(0,10),sales:sl.map(s=>({...s,items:JSON.parse(s.items)})),logs:l})});
a.get('/api/settings',A,(r,_)=>_.json(d.settings));
a.put('/api/settings',A,SA,(r,_)=>{Object.assign(d.settings,r.body);S();_.json({success:true})});
a.get('*',(r,_)=>{if(r.path.startsWith('/api/'))return _.status(404).json({error:'Not found'});_.sendFile(p.join(__dirname,'public','index.html'))});
a.listen(O,'0.0.0.0',()=>{console.log('🏪 v3.1');console.log('📡 '+O);console.log('🔑 admin/admin');console.log('📁 '+P)});
